name: CI & Deploy



on:

  push:

    branches:


      - master



jobs:

  build-test-deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Build dev image (with tests)

        run: docker build --target builder -t myapp:dev .



      - name: Save dev image to tar

        run: docker save myapp:dev -o myapp_dev.tar



      - name: Build prod image

        run: docker build -t myapp:latest .



      - name: Save prod image to tar

        run: docker save myapp:latest -o myapp_latest.tar


      # 5) Deploy to remote server via Podman
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          # Сохраняем и передаём образ на сервер
          docker save myapp:latest | \
            ssh -o StrictHostKeyChecking=no \
                -p ${{ secrets.SSH_PORT }} \
                ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "podman load && \
             podman stop myapp || true && \
             podman rm myapp   || true && \
             podman tag myapp:latest myapp:latest && \
             podman run -d \
               --name myapp \
               --network host \
               myapp:latest \
               uvicorn src.main:app --host 0.0.0.0 --port 8096"
