name: CI & Deploy

on:
  push:
    branches: [main]

jobs:
  build-push-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Build Docker image
      - name: Build image
        run: |
          docker build -t $IMAGE_NAME .

      # 4) Run tests inside container
      - name: Run tests
        run: |
          docker run --rm $IMAGE_NAME pytest tests

      # 5) Deploy to remote server via Podman
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          # Сохраняем и передаём образ на сервер
          docker save $IMAGE_NAME | \
            ssh -o StrictHostKeyChecking=no \
                -p ${{ secrets.SSH_PORT }} \
                ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "podman load && \
             podman stop myapp || true && \
             podman rm myapp   || true && \
             podman tag $IMAGE_NAME:$GITHUB_SHA myapp:latest && \
             podman run -d \
               --name myapp \
               --network host \
               myapp:latest \
               uvicorn src.main:app --host 0.0.0.0 --port 8096"
